# These are supported funding model platforms

ko_fi: andrath
xmr: 44Rqjj4FQVyVg3YPXRExHz7r2v5kHT1wqczVSiiJ8jHQhrx3qGTwcCSFjkbS5t4tMtSAuV9xX1ZMeiwzj9ih3x4oCsxJUdq
btc: bc1qxu6wdq0gw8ssytxn65uptmar8a58p9ugtz3gsw
